repos:
- repo: local
  hooks:
  - id: vault-fix
    name: Vault fix
    entry: uv run --no-sync vaultspec-core vault check all --fix
    types:
    - markdown
    language: system
    pass_filenames: false
  - id: vault-sanitize-annotations
    name: Vault sanitize annotations
    entry: uv run --no-sync vaultspec-core vault sanitize annotations
    types:
    - markdown
    language: system
    pass_filenames: false
  - id: check-provider-artifacts
    name: Check provider artifacts
    entry: uv run --no-sync vaultspec-core check-providers
    always_run: true
    language: system
    pass_filenames: false
  - id: spec-check
    name: Spec check
    entry: uv run --no-sync vaultspec-core spec doctor
    types:
    - markdown
    language: system
    pass_filenames: false
