#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-format"
name = "Ruff format"
entry = "uv run --no-sync ruff format"
language = "system"
always_run = true
pass_filenames = false

[[repos.hooks]]
id = "ruff-check"
name = "Ruff check and fix"
entry = "uv run --no-sync ruff check --fix"
language = "system"
always_run = true
pass_filenames = false

[[repos.hooks]]
id = "ty-check"
name = "ty check"
entry = "uv run --no-sync python -m ty check"
language = "system"
always_run = true
pass_filenames = false
